apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis-app
  namespace: stateful-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-redis-app
  template:
    metadata:
      labels:
        app: node-redis-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: app
          image: sonalijain0605/stateful-app
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: APP_NAME
              value: "node_redis_app"      # Direct value
            - name: REDIS_HOST
              value: "redis"               # Redis service name
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet: { path: /readyz, port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 10

