apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-redis-app
  namespace: stateful-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-redis-app
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70

