apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: stateful-demo
spec:
  clusterIP: None   # Makes it headless
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379

